name: PR-check

on:
  push:
    branches: [ master, develop ]
  pull_request:
    types: [opened, synchronize, reopended]

jobs:
  sonard_cloud:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install modules
      run: npm i
    
    - name: Build project
      run: npm run build

    # when lint error will be fixed - add step with lint as well

    - name: Run unit tests
      run: npm run test:cover
    
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: a81a0f0e8452e520a1067e4eed2669d10f059b7a
        SONAR_HOST_URL: https://sonarcloud.io
